---

- name: Add server user with home directory.
  ansible.builtin.user:
    append: yes
    create_home: yes
    groups: "{{ user_group }}"
    name: "{{ server_user }}"
    password: "{{ server_user_password }}"
    state: present
    shell: /bin/bash
    update_password: always
  become: yes
  tags: ["deploy", "dwapi", "prelude"]

